;; Test-only scaffolding/invariants appended to the full CURRENT vault source.
(define-map context (string-ascii 100) { called: uint })
(define-public (update-context (name (string-ascii 100)) (called uint))
  (ok (map-set context name { called: called })))
(define-public (rv-admin (action uint) (raw uint))
  (begin
    (asserts! (is-eq contract-caller POOL) ERR_UNAUTHORIZED)
    (let ((a (mod action u12)) (amount (+ u1 (mod raw u1000000))))
      (if (is-eq a u0)
        (begin
          (try! (contract-call? .mock-ft mint amount POOL))
          (try! (fund amount)) true)
      (if (is-eq a u1) (begin (try! (set-window-blocks (mod raw u1009))) true)
      (if (is-eq a u2) (begin (try! (set-no-pyth-slippage-bps (mod raw u5001))) true)
      (if (is-eq a u3) (begin (try! (router-swap-split-dia amount amount u0 u0)) true)
      (if (is-eq a u4) (begin (try! (finish)) true)
      (if (is-eq a u5) (begin (try! (emergency-recover)) true)
      (if (is-eq a u6) (begin (try! (jing-refloor 0x)) true)
      (if (is-eq a u7) (begin (try! (jing-take amount 0x)) true)
      (if (is-eq a u8) (begin (try! (router-swap-split amount u0 amount u0 u0 0x)) true)
      (if (is-eq a u9) (begin (try! (set-leeway-bps (mod raw u1001))) true)
      (if (is-eq a u10) (begin (try! (set-slippage-bps (mod raw u1001))) true)
        (begin (try! (set-router-cooldown (mod raw u145))) true))))))))))))
    (ok true)))

)
(define-public (rv-donate (raw uint))
  (contract-call? .mock-ft mint (+ u1 (mod raw u1000000)) current-contract))
(define-public (rv-fund-router (raw uint))
  (stx-transfer? (+ u1 (mod raw u1000000000)) tx-sender .mock-router))
(define-public (rv-release-window)
  (begin (asserts! (is-eq contract-caller POOL) ERR_UNAUTHORIZED)
    (ok (var-set window-blocks u0))))
(define-public (rv-world (raw uint))
  (begin
    (try! (contract-call? .mock-dia set-stale (is-eq (mod raw u7) u0)))
    (try! (contract-call? .mock-dia set-failed (is-eq (mod raw u11) u0)))
    (try! (contract-call? .mock-native set-failed (is-eq (mod raw u13) u0)))
    (try! (contract-call? .mock-native set-mid (if (is-eq (mod raw u17) u0) u0 u32000000000000)))
    (contract-call? .mock-dia set-skew (+ u8000 (mod raw u5000)))))
;; Reachable successful round trips as well as unconstrained failing calls.
(define-public (rv-batch (raw uint))
  (begin
    (asserts! (is-eq contract-caller POOL) ERR_UNAUTHORIZED)
    ;; Test-only expiry progression; production's mid-batch setter lock remains
    ;; covered by strict runtime/fork tests. Drain donations too, not just fund.
    (var-set window-blocks u0)
    (try! (set-router-cooldown u0))
    (try! (set-max-chunk-sats MAX_CHUNK_SATS))
    (try! (set-no-pyth-slippage-bps u5000))
    (if (is-none (var-get batch-start))
      (begin (try! (rv-admin u0 (mod raw u10000))) true) true)
    (let ((amount (sbtc-balance)))
      (try! (stx-transfer? (* amount u3200) tx-sender .mock-router))
      (try! (router-swap-split-dia amount amount u0 u0)))
    (finish)))
(define-read-only (invariant-window-exclusive)
  (not (and (window-open) (window-elapsed))))
(define-read-only (invariant-no-clock-no-window)
  (or (is-some (var-get batch-start)) (and (not (window-open)) (not (window-elapsed)))))
(define-read-only (invariant-clock-not-future)
  (match (var-get batch-start) start (<= start burn-block-height) true))
(define-read-only (invariant-cooldown-not-future)
  (<= (var-get last-router-swap) burn-block-height))
(define-read-only (invariant-config-bounded)
  (and (<= (var-get window-blocks) MAX_WINDOW_BLOCKS)
       (<= (var-get no-pyth-slippage-bps) MAX_NO_PYTH_SLIPPAGE_BPS)
       (<= (var-get leeway-bps) MAX_LEEWAY_BPS)
       (<= (var-get slippage-bps) MAX_SLIPPAGE_BPS)
       (<= (var-get dia-band-bps) MAX_DIA_BAND_BPS)
       (> (var-get max-chunk-sats) u0)
       (<= (var-get max-chunk-sats) MAX_CHUNK_SATS)
       (<= (var-get router-cooldown-blocks) MAX_COOLDOWN_BLOCKS)))
(define-read-only (invariant-emergency-price-floor)
  (match (get-no-pyth-price)
    price (and (> (get limit price) u0) (<= (get limit price) (get mid price))
      (if (is-eq (get source price) "native")
        (is-eq (get limit price) (/ (get mid price) u2))
        (is-eq (get limit price) (/ (* (get mid price) (- BPS_PRECISION (var-get no-pyth-slippage-bps))) BPS_PRECISION))))
    err-code true))
(define-read-only (invariant-no-clock-no-market-position)
  (or (is-some (var-get batch-start))
      (and (is-eq (contract-call? .v6-market get-token-x-deposit (contract-call? .v6-market get-current-cycle) current-contract) u0)
           (is-eq (contract-call? .v6-market get-token-x-parked current-contract) u0))))
(define-read-only (invariant-ft-conservation)
  (is-eq (unwrap-panic (contract-call? .mock-ft get-total-supply))
    (+ (unwrap-panic (contract-call? .mock-ft get-balance current-contract))
       (unwrap-panic (contract-call? .mock-ft get-balance POOL))
       (unwrap-panic (contract-call? .mock-ft get-balance .v6-market))
       (unwrap-panic (contract-call? .mock-ft get-balance .mock-router)))))
